# -*- coding: utf-8 -*-
"""Untitled102.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ljKF2m1SIrCfiAjGK-4-VZvcZKKj5ByF
"""

import nltk
from nltk.chat.util import Chat, reflections

# Define pairs of patterns and responses
pairs = [
    [
        r"my name is (.*)",
        ["Hello %1, how can I help you today?",]
    ],
    [
        r"what is your name?",
        ["My name is Chatbot and I'm here to assist you.",]
    ],
    [
        r"how are you ?",
        ["I'm doing well, thank you!", "I'm doing great, how about you?",]
    ],
    [
        r"sorry (.*)",
        ["It's okay, no need to apologize.", "No problem.",]
    ],
    [
        r"(.*) (good|well)",
        ["That's great to hear!", "Awesome!",]
    ],
    [
        r"(.*)",
        ["Sorry, I didn't understand that. Can you please rephrase?",]
    ],
]

# Create a Chat instance
chatbot = Chat(pairs, reflections)

# Define a function to interact with the chatbot
def chat():
    print("Hi! I'm Chatbot. How can I assist you today?")
    while True:
        user_input = input("You: ")
        if user_input.lower() == "exit":
            print("Goodbye!")
            break
        else:
            print("Chatbot:", chatbot.respond(user_input))

# Call the chat function to start the conversation
if __name__ == "__main__":
    chat()





